module.exports={
  name:"بقالة العزي للمواد الغذائية",
  slug:"bagalah-alizzi",
  version:"3.0.0",
  orientation:"portrait",
  icon:"./assets/images/android-icon-foreground.png",
  userInterfaceStyle:"light",
  backgroundColor:"#F4F7F4",
  primaryColor:"#126B4A",
  android:{
    package:"com.app.bagalahalizzi",
    versionCode:300,
    adaptiveIcon:{
      backgroundColor:"#F4F7F4",
      foregroundImage:"./assets/images/android-icon-foreground.png",
      backgroundImage:"./assets/images/android-icon-background.png",
      monochromeImage:"./assets/images/android-icon-monochrome.png"
    },
    softwareKeyboardLayoutMode:"resize",
    permissions:["POST_NOTIFICATIONS"]
  },
  androidStatusBar:{barStyle:"light-content",backgroundColor:"#0B4D36",translucent:false},
  androidNavigationBar:{backgroundColor:"#F4F7F4",barStyle:"dark-content",enforceContrast:false},
  plugins:[
    "expo-build-properties",
    ["expo-splash-screen",{backgroundColor:"#0B4D36",image:"./assets/images/android-icon-foreground.png",imageWidth:160,resizeMode:"contain"}]
  ],
  experiments:{reactCompiler:false}
};