ALTER TABLE store_settings
  ADD COLUMN logoUrl TEXT NULL,
  ADD COLUMN autoPrint BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN printCopies INT NOT NULL DEFAULT 1,
  ADD COLUMN showLogoOnReceipt BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN showUnitPriceOnReceipt BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN reportDefaultRange VARCHAR(20) NOT NULL DEFAULT 'month',
  ADD COLUMN lowStockAlerts BOOLEAN NOT NULL DEFAULT TRUE;
