import { boolean, decimal, index, int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export const categories = mysqlTable("categories", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull().unique(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const products = mysqlTable("products", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 200 }).notNull(), barcode: varchar("barcode", { length: 80 }).unique(), categoryId: int("categoryId"), unit: varchar("unit", { length: 40 }).default("حبة").notNull(), purchasePrice: decimal("purchasePrice", { precision: 12, scale: 2 }).default("0").notNull(), salePrice: decimal("salePrice", { precision: 12, scale: 2 }).default("0").notNull(), stock: decimal("stock", { precision: 12, scale: 3 }).default("0").notNull(), minStock: decimal("minStock", { precision: 12, scale: 3 }).default("0").notNull(), active: boolean("active").default(true).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ nameIdx: index("products_name_idx").on(t.name) }));
export const customers = mysqlTable("customers", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 200 }).notNull(), phone: varchar("phone", { length: 40 }), address: varchar("address", { length: 255 }), openingBalance: decimal("openingBalance", { precision: 12, scale: 2 }).default("0").notNull(), notes: text("notes"), active: boolean("active").default(true).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() }, (t) => ({ nameIdx: index("customers_name_idx").on(t.name), phoneIdx: index("customers_phone_idx").on(t.phone) }));
export const suppliers = mysqlTable("suppliers", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 200 }).notNull(), phone: varchar("phone", { length: 40 }), address: varchar("address", { length: 255 }), openingBalance: decimal("openingBalance", { precision: 12, scale: 2 }).default("0").notNull(), notes: text("notes"), active: boolean("active").default(true).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const salesInvoices = mysqlTable("sales_invoices", { id: int("id").autoincrement().primaryKey(), invoiceNo: varchar("invoiceNo", { length: 40 }).notNull().unique(), customerId: int("customerId"), paymentType: mysqlEnum("paymentType", ["cash", "credit", "partial"]).default("cash").notNull(), subtotal: decimal("subtotal", { precision: 14, scale: 2 }).notNull(), discount: decimal("discount", { precision: 14, scale: 2 }).default("0").notNull(), paid: decimal("paid", { precision: 14, scale: 2 }).default("0").notNull(), total: decimal("total", { precision: 14, scale: 2 }).notNull(), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ dateIdx: index("sales_invoice_date_idx").on(t.createdAt), customerIdx: index("sales_invoice_customer_idx").on(t.customerId) }));
export const salesInvoiceItems = mysqlTable("sales_invoice_items", { id: int("id").autoincrement().primaryKey(), invoiceId: int("invoiceId").notNull(), productId: int("productId").notNull(), productName: varchar("productName", { length: 200 }).notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull(), unitPrice: decimal("unitPrice", { precision: 12, scale: 2 }).notNull(), purchasePrice: decimal("purchasePrice", { precision: 12, scale: 2 }).default("0").notNull(), total: decimal("total", { precision: 14, scale: 2 }).notNull() });
export const purchaseInvoices = mysqlTable("purchase_invoices", { id: int("id").autoincrement().primaryKey(), invoiceNo: varchar("invoiceNo", { length: 40 }).notNull().unique(), supplierId: int("supplierId"), paymentType: mysqlEnum("paymentType", ["cash", "credit", "partial"]).default("cash").notNull(), total: decimal("total", { precision: 14, scale: 2 }).notNull(), paid: decimal("paid", { precision: 14, scale: 2 }).default("0").notNull(), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const purchaseInvoiceItems = mysqlTable("purchase_invoice_items", { id: int("id").autoincrement().primaryKey(), invoiceId: int("invoiceId").notNull(), productId: int("productId").notNull(), productName: varchar("productName", { length: 200 }).notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull(), unitPrice: decimal("unitPrice", { precision: 12, scale: 2 }).notNull(), total: decimal("total", { precision: 14, scale: 2 }).notNull() });
export const freeInvoices = mysqlTable("free_invoices", { id: int("id").autoincrement().primaryKey(), invoiceNo: varchar("invoiceNo", { length: 40 }).notNull().unique(), customerName: varchar("customerName", { length: 200 }), notes: text("notes"), total: decimal("total", { precision: 14, scale: 2 }).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ dateIdx: index("free_invoice_date_idx").on(t.createdAt) }));
export const freeInvoiceItems = mysqlTable("free_invoice_items", { id: int("id").autoincrement().primaryKey(), invoiceId: int("invoiceId").notNull(), description: varchar("description", { length: 255 }).notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull(), unitPrice: decimal("unitPrice", { precision: 14, scale: 2 }).notNull(), total: decimal("total", { precision: 14, scale: 2 }).notNull() });
export const customerPayments = mysqlTable("customer_payments", { id: int("id").autoincrement().primaryKey(), customerId: int("customerId").notNull(), amount: decimal("amount", { precision: 14, scale: 2 }).notNull(), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const supplierPayments = mysqlTable("supplier_payments", { id: int("id").autoincrement().primaryKey(), supplierId: int("supplierId").notNull(), amount: decimal("amount", { precision: 14, scale: 2 }).notNull(), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const expenses = mysqlTable("expenses", { id: int("id").autoincrement().primaryKey(), category: varchar("category", { length: 100 }).notNull(), amount: decimal("amount", { precision: 14, scale: 2 }).notNull(), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() }, (t) => ({ dateIdx: index("expenses_date_idx").on(t.createdAt) }));
export const stockMovements = mysqlTable("stock_movements", { id: int("id").autoincrement().primaryKey(), productId: int("productId").notNull(), type: mysqlEnum("type", ["sale", "purchase", "adjustment", "return"]).notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull(), referenceId: int("referenceId"), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const storeSettings = mysqlTable("store_settings", { id: int("id").autoincrement().primaryKey(), storeName: varchar("storeName", { length: 200 }).default("بقالة العزي للمواد الغذائية").notNull(), phone: varchar("phone", { length: 40 }), address: varchar("address", { length: 255 }), currency: varchar("currency", { length: 20 }).default("ر.س").notNull(), receiptWidth: mysqlEnum("receiptWidth", ["58mm", "80mm"]).default("80mm").notNull(), logoUrl: text("logoUrl"), autoPrint: boolean("autoPrint").default(false).notNull(), printCopies: int("printCopies").default(1).notNull(), showLogoOnReceipt: boolean("showLogoOnReceipt").default(true).notNull(), showUnitPriceOnReceipt: boolean("showUnitPriceOnReceipt").default(false).notNull(), reportDefaultRange: varchar("reportDefaultRange", { length: 20 }).default("month").notNull(), lowStockAlerts: boolean("lowStockAlerts").default(true).notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Product = typeof products.$inferSelect; export type Customer = typeof customers.$inferSelect; export type Supplier = typeof suppliers.$inferSelect; export type SalesInvoice = typeof salesInvoices.$inferSelect;