import { COOKIE_NAME } from "../shared/const.js";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { getDb } from "./db";
import { and, desc, eq, gte, lt, sql } from "drizzle-orm";
import { z } from "zod";
import { categories, customerPayments, customers, expenses, freeInvoiceItems, freeInvoices, products, purchaseInvoiceItems, purchaseInvoices, salesInvoiceItems, salesInvoices, stockMovements, storeSettings, suppliers, supplierPayments } from "../drizzle/schema";

const money = z.number().finite().nonnegative();
const qty = z.number().finite().positive();
const itemInput = z.object({ productId: z.number().int().positive(), quantity: qty });
const freeItemInput = z.object({ description: z.string().min(1).max(255), quantity: qty, unitPrice: money });
const dbOrThrow = async () => { const db = await getDb(); if (!db) throw new Error("DATABASE_UNAVAILABLE"); return db; };

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query((opts) => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),

  products: router({
    list: protectedProcedure.input(z.object({ search: z.string().optional(), activeOnly: z.boolean().default(true) }).optional()).query(async ({ input }) => { const db = await dbOrThrow(); const rows = await db.select().from(products).where(input?.activeOnly === false ? undefined : eq(products.active, true)).orderBy(desc(products.updatedAt)); const q = input?.search?.trim().toLowerCase(); return q ? rows.filter((p) => p.name.toLowerCase().includes(q) || (p.barcode ?? "").includes(q)) : rows; }),
    create: protectedProcedure.input(z.object({ name: z.string().min(1).max(200), barcode: z.string().max(80).optional(), categoryId: z.number().int().positive().optional(), unit: z.string().max(40).default("حبة"), purchasePrice: money.default(0), salePrice: money, stock: z.number().nonnegative().default(0), minStock: z.number().nonnegative().default(0) })).mutation(async ({ input }) => { const db = await dbOrThrow(); const result = await db.insert(products).values({ ...input, purchasePrice: input.purchasePrice.toFixed(2), salePrice: input.salePrice.toFixed(2), stock: input.stock.toFixed(3), minStock: input.minStock.toFixed(3), barcode: input.barcode || null }); const id = Number(result[0].insertId); if (input.stock > 0) await db.insert(stockMovements).values({ productId: id, type: "adjustment", quantity: input.stock.toFixed(3), notes: "الرصيد الافتتاحي" }); return (await db.select().from(products).where(eq(products.id, id)).limit(1))[0]; }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(1).max(200), barcode: z.string().max(80).optional(), categoryId: z.number().int().positive().optional(), unit: z.string().max(40), purchasePrice: money, salePrice: money, minStock: z.number().nonnegative() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.update(products).set({ name: input.name, barcode: input.barcode || null, categoryId: input.categoryId ?? null, unit: input.unit, purchasePrice: input.purchasePrice.toFixed(2), salePrice: input.salePrice.toFixed(2), minStock: input.minStock.toFixed(3) }).where(eq(products.id, input.id)); return (await db.select().from(products).where(eq(products.id, input.id)).limit(1))[0]; }),
    delete: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.update(products).set({ active: false }).where(eq(products.id, input.id)); return { success: true }; }),
  }),

  categories: router({ list: protectedProcedure.query(async () => (await dbOrThrow()).select().from(categories).orderBy(categories.name)), create: protectedProcedure.input(z.object({ name: z.string().min(1).max(120) })).mutation(async ({ input }) => { const db = await dbOrThrow(); const r = await db.insert(categories).values({ name: input.name.trim() }); return (await db.select().from(categories).where(eq(categories.id, Number(r[0].insertId))).limit(1))[0]; }) }),

  customers: router({
    list: protectedProcedure.input(z.object({ search: z.string().optional() }).optional()).query(async ({ input }) => { const db = await dbOrThrow(); const rows = await db.select().from(customers).where(eq(customers.active, true)).orderBy(desc(customers.updatedAt)); const invoices = await db.select({ customerId: salesInvoices.customerId, total: salesInvoices.total, paid: salesInvoices.paid }).from(salesInvoices).where(sql`${salesInvoices.customerId} IS NOT NULL`); const payments = await db.select({ customerId: customerPayments.customerId, amount: customerPayments.amount }).from(customerPayments); const balances = new Map<number, number>(); for (const i of invoices) if (i.customerId) balances.set(i.customerId, (balances.get(i.customerId) ?? 0) + Number(i.total) - Number(i.paid)); for (const p of payments) balances.set(p.customerId, (balances.get(p.customerId) ?? 0) - Number(p.amount)); const q = input?.search?.trim().toLowerCase(); return rows.filter((c) => !q || c.name.toLowerCase().includes(q) || (c.phone ?? "").includes(q)).map((c) => ({ ...c, balance: Number(c.openingBalance) + (balances.get(c.id) ?? 0) })); }),
    create: protectedProcedure.input(z.object({ name: z.string().min(1).max(200), phone: z.string().max(40).optional(), address: z.string().max(255).optional(), openingBalance: money.default(0), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); const r = await db.insert(customers).values({ ...input, phone: input.phone || null, address: input.address || null, openingBalance: input.openingBalance.toFixed(2) }); return (await db.select().from(customers).where(eq(customers.id, Number(r[0].insertId))).limit(1))[0]; }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(1), phone: z.string().optional(), address: z.string().optional(), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.update(customers).set({ name: input.name, phone: input.phone || null, address: input.address || null, notes: input.notes || null }).where(eq(customers.id, input.id)); return { success: true }; }),
    payment: protectedProcedure.input(z.object({ customerId: z.number().int().positive(), amount: money.refine((v) => v > 0), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); const r = await db.insert(customerPayments).values({ customerId: input.customerId, amount: input.amount.toFixed(2), notes: input.notes }); return { id: Number(r[0].insertId), success: true }; }),
    updatePayment: protectedProcedure.input(z.object({ id: z.number().int().positive(), amount: money.refine((v) => v > 0), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.update(customerPayments).set({ amount: input.amount.toFixed(2), notes: input.notes }).where(eq(customerPayments.id, input.id)); return { success: true }; }),
    deletePayment: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.delete(customerPayments).where(eq(customerPayments.id, input.id)); return { success: true }; }),
    account: protectedProcedure.input(z.object({ customerId: z.number().int().positive() })).query(async ({ input }) => { const db = await dbOrThrow(); const customer = (await db.select().from(customers).where(eq(customers.id, input.customerId)).limit(1))[0]; const invoices = await db.select().from(salesInvoices).where(eq(salesInvoices.customerId, input.customerId)).orderBy(desc(salesInvoices.createdAt)); const payments = await db.select().from(customerPayments).where(eq(customerPayments.customerId, input.customerId)).orderBy(desc(customerPayments.createdAt)); const invoiceTotal = invoices.reduce((s, x) => s + Number(x.total), 0); const paid = payments.reduce((s, x) => s + Number(x.amount), 0) + invoices.reduce((s, x) => s + Number(x.paid), 0); return { customer, invoices, payments, balance: Number(customer?.openingBalance ?? 0) + invoiceTotal - paid }; }),
  }),

  suppliers: router({ list: protectedProcedure.query(async () => (await dbOrThrow()).select().from(suppliers).where(eq(suppliers.active, true)).orderBy(suppliers.name)), create: protectedProcedure.input(z.object({ name: z.string().min(1), phone: z.string().optional(), address: z.string().optional(), openingBalance: money.default(0), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); const r = await db.insert(suppliers).values({ ...input, phone: input.phone || null, address: input.address || null, openingBalance: input.openingBalance.toFixed(2) }); return (await db.select().from(suppliers).where(eq(suppliers.id, Number(r[0].insertId))).limit(1))[0]; }), payment: protectedProcedure.input(z.object({ supplierId: z.number().int().positive(), amount: money.refine((v) => v > 0), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.insert(supplierPayments).values({ supplierId: input.supplierId, amount: input.amount.toFixed(2), notes: input.notes }); return { success: true }; }) }),

  sales: router({
    recent: protectedProcedure.input(z.object({ limit: z.number().int().min(1).max(100).default(50) }).optional()).query(async ({ input }) => (await dbOrThrow()).select().from(salesInvoices).orderBy(desc(salesInvoices.createdAt)).limit(input?.limit ?? 50)),
    detail: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ input }) => { const db = await dbOrThrow(); const invoice = (await db.select().from(salesInvoices).where(eq(salesInvoices.id, input.id)).limit(1))[0]; if (!invoice) throw new Error("INVOICE_NOT_FOUND"); const items = await db.select().from(salesInvoiceItems).where(eq(salesInvoiceItems.invoiceId, input.id)); const customer = invoice.customerId ? (await db.select().from(customers).where(eq(customers.id, invoice.customerId)).limit(1))[0] : null; return { invoice, items, customer }; }),
    create: protectedProcedure.input(z.object({ customerId: z.number().int().positive().nullable().default(null), paymentType: z.enum(["cash", "credit", "partial"]).default("cash"), paid: money.default(0), discount: money.default(0), notes: z.string().optional(), items: z.array(itemInput).min(1) })).mutation(async ({ input }) => { const db = await dbOrThrow(); return db.transaction(async (tx) => { const all = await tx.select().from(products).where(eq(products.active, true)); const lines = input.items.map((i) => { const p = all.find((x) => x.id === i.productId); if (!p) throw new Error("PRODUCT_NOT_FOUND"); if (Number(p.stock) < i.quantity) throw new Error(`INSUFFICIENT_STOCK:${p.name}`); const total = Number(p.salePrice) * i.quantity; return { p, q: i.quantity, total }; }); const subtotal = lines.reduce((s, x) => s + x.total, 0); const total = Math.max(0, subtotal - input.discount); if (input.paid > total) throw new Error("PAID_EXCEEDS_TOTAL"); const invoiceNo = `S-${Date.now()}`; const r = await tx.insert(salesInvoices).values({ invoiceNo, customerId: input.customerId, paymentType: input.paymentType, subtotal: subtotal.toFixed(2), discount: input.discount.toFixed(2), paid: input.paid.toFixed(2), total: total.toFixed(2), notes: input.notes }); const invoiceId = Number(r[0].insertId); for (const line of lines) { await tx.insert(salesInvoiceItems).values({ invoiceId, productId: line.p.id, productName: line.p.name, quantity: line.q.toFixed(3), unitPrice: Number(line.p.salePrice).toFixed(2), purchasePrice: Number(line.p.purchasePrice).toFixed(2), total: line.total.toFixed(2) }); await tx.update(products).set({ stock: sql`${products.stock} - ${line.q}` }).where(eq(products.id, line.p.id)); await tx.insert(stockMovements).values({ productId: line.p.id, type: "sale", quantity: (-line.q).toFixed(3), referenceId: invoiceId }); } return { id: invoiceId, invoiceNo, total, paid: input.paid, due: total - input.paid, items: lines.map((x) => ({ name: x.p.name, quantity: x.q, unitPrice: Number(x.p.salePrice), total: x.total })) }; }); }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), customerId: z.number().int().positive().nullable().default(null), paymentType: z.enum(["cash", "credit", "partial"]), paid: money, discount: money, notes: z.string().optional(), items: z.array(itemInput).min(1) })).mutation(async ({ input }) => { const db = await dbOrThrow(); return db.transaction(async (tx) => { const old = (await tx.select().from(salesInvoices).where(eq(salesInvoices.id, input.id)).limit(1))[0]; if (!old) throw new Error("INVOICE_NOT_FOUND"); const oldItems = await tx.select().from(salesInvoiceItems).where(eq(salesInvoiceItems.invoiceId, input.id)); for (const line of oldItems) await tx.update(products).set({ stock: sql`${products.stock} + ${Number(line.quantity)}` }).where(eq(products.id, line.productId)); await tx.delete(salesInvoiceItems).where(eq(salesInvoiceItems.invoiceId, input.id)); await tx.delete(stockMovements).where(eq(stockMovements.referenceId, input.id)); const all = await tx.select().from(products).where(eq(products.active, true)); const lines = input.items.map((i) => { const p = all.find((x) => x.id === i.productId); if (!p) throw new Error("PRODUCT_NOT_FOUND"); if (Number(p.stock) < i.quantity) throw new Error(`INSUFFICIENT_STOCK:${p.name}`); const total = Number(p.salePrice) * i.quantity; return { p, q: i.quantity, total }; }); const subtotal = lines.reduce((s, x) => s + x.total, 0); const total = Math.max(0, subtotal - input.discount); if (input.paid > total) throw new Error("PAID_EXCEEDS_TOTAL"); await tx.update(salesInvoices).set({ customerId: input.customerId, paymentType: input.paymentType, subtotal: subtotal.toFixed(2), discount: input.discount.toFixed(2), paid: input.paid.toFixed(2), total: total.toFixed(2), notes: input.notes }).where(eq(salesInvoices.id, input.id)); for (const line of lines) { await tx.insert(salesInvoiceItems).values({ invoiceId: input.id, productId: line.p.id, productName: line.p.name, quantity: line.q.toFixed(3), unitPrice: Number(line.p.salePrice).toFixed(2), purchasePrice: Number(line.p.purchasePrice).toFixed(2), total: line.total.toFixed(2) }); await tx.update(products).set({ stock: sql`${products.stock} - ${line.q}` }).where(eq(products.id, line.p.id)); await tx.insert(stockMovements).values({ productId: line.p.id, type: "sale", quantity: (-line.q).toFixed(3), referenceId: input.id }); } return { success: true }; }); }),
    delete: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await dbOrThrow(); return db.transaction(async (tx) => { const items = await tx.select().from(salesInvoiceItems).where(eq(salesInvoiceItems.invoiceId, input.id)); for (const line of items) await tx.update(products).set({ stock: sql`${products.stock} + ${Number(line.quantity)}` }).where(eq(products.id, line.productId)); await tx.delete(stockMovements).where(eq(stockMovements.referenceId, input.id)); await tx.delete(salesInvoiceItems).where(eq(salesInvoiceItems.invoiceId, input.id)); await tx.delete(salesInvoices).where(eq(salesInvoices.id, input.id)); return { success: true }; }); }),
  }),

  freeInvoices: router({
    recent: protectedProcedure.input(z.object({ limit: z.number().int().min(1).max(100).default(50) }).optional()).query(async ({ input }) => (await dbOrThrow()).select().from(freeInvoices).orderBy(desc(freeInvoices.createdAt)).limit(input?.limit ?? 50)),
    detail: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ input }) => { const db = await dbOrThrow(); const invoice = (await db.select().from(freeInvoices).where(eq(freeInvoices.id, input.id)).limit(1))[0]; if (!invoice) throw new Error("FREE_INVOICE_NOT_FOUND"); const items = await db.select().from(freeInvoiceItems).where(eq(freeInvoiceItems.invoiceId, input.id)); return { invoice, items }; }),
    create: protectedProcedure.input(z.object({ customerName: z.string().max(200).optional(), notes: z.string().optional(), items: z.array(freeItemInput).min(1) })).mutation(async ({ input }) => { const db = await dbOrThrow(); return db.transaction(async (tx) => { const total = input.items.reduce((s, x) => s + x.quantity * x.unitPrice, 0); const invoiceNo = `F-${Date.now()}`; const r = await tx.insert(freeInvoices).values({ invoiceNo, customerName: input.customerName || null, notes: input.notes, total: total.toFixed(2) }); const id = Number(r[0].insertId); for (const item of input.items) await tx.insert(freeInvoiceItems).values({ invoiceId: id, description: item.description, quantity: item.quantity.toFixed(3), unitPrice: item.unitPrice.toFixed(2), total: (item.quantity * item.unitPrice).toFixed(2) }); return { id, invoiceNo, total }; }); }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), customerName: z.string().max(200).optional(), notes: z.string().optional(), items: z.array(freeItemInput).min(1) })).mutation(async ({ input }) => { const db = await dbOrThrow(); return db.transaction(async (tx) => { const total = input.items.reduce((s, x) => s + x.quantity * x.unitPrice, 0); await tx.update(freeInvoices).set({ customerName: input.customerName || null, notes: input.notes, total: total.toFixed(2) }).where(eq(freeInvoices.id, input.id)); await tx.delete(freeInvoiceItems).where(eq(freeInvoiceItems.invoiceId, input.id)); for (const item of input.items) await tx.insert(freeInvoiceItems).values({ invoiceId: input.id, description: item.description, quantity: item.quantity.toFixed(3), unitPrice: item.unitPrice.toFixed(2), total: (item.quantity * item.unitPrice).toFixed(2) }); return { success: true }; }); }),
    delete: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.delete(freeInvoiceItems).where(eq(freeInvoiceItems.invoiceId, input.id)); await db.delete(freeInvoices).where(eq(freeInvoices.id, input.id)); return { success: true }; }),
  }),

  purchases: router({ create: protectedProcedure.input(z.object({ supplierId: z.number().int().positive().nullable().default(null), paymentType: z.enum(["cash", "credit", "partial"]).default("cash"), paid: money.default(0), notes: z.string().optional(), items: z.array(z.object({ productId: z.number().int().positive(), quantity: qty, unitPrice: money })).min(1) })).mutation(async ({ input }) => { const db = await dbOrThrow(); return db.transaction(async (tx) => { const all = await tx.select().from(products); const lines = input.items.map((i) => { const p = all.find((x) => x.id === i.productId); if (!p) throw new Error("PRODUCT_NOT_FOUND"); return { p, q: i.quantity, unitPrice: i.unitPrice, total: i.quantity * i.unitPrice }; }); const total = lines.reduce((s, x) => s + x.total, 0); if (input.paid > total) throw new Error("PAID_EXCEEDS_TOTAL"); const invoiceNo = `P-${Date.now()}`; const r = await tx.insert(purchaseInvoices).values({ invoiceNo, supplierId: input.supplierId, paymentType: input.paymentType, total: total.toFixed(2), paid: input.paid.toFixed(2), notes: input.notes }); const invoiceId = Number(r[0].insertId); for (const line of lines) { await tx.insert(purchaseInvoiceItems).values({ invoiceId, productId: line.p.id, productName: line.p.name, quantity: line.q.toFixed(3), unitPrice: line.unitPrice.toFixed(2), total: line.total.toFixed(2) }); await tx.update(products).set({ stock: sql`${products.stock} + ${line.q}`, purchasePrice: line.unitPrice.toFixed(2) }).where(eq(products.id, line.p.id)); await tx.insert(stockMovements).values({ productId: line.p.id, type: "purchase", quantity: line.q.toFixed(3), referenceId: invoiceId }); } return { id: invoiceId, invoiceNo, total }; }); }) }),

  expenses: router({ list: protectedProcedure.query(async () => (await dbOrThrow()).select().from(expenses).orderBy(desc(expenses.createdAt)).limit(200)), create: protectedProcedure.input(z.object({ category: z.string().min(1).max(100), amount: money.refine((v) => v > 0), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); const r = await db.insert(expenses).values({ ...input, amount: input.amount.toFixed(2) }); return { id: Number(r[0].insertId) }; }), update: protectedProcedure.input(z.object({ id: z.number().int().positive(), category: z.string().min(1).max(100), amount: money.refine((v) => v > 0), notes: z.string().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.update(expenses).set({ category: input.category, amount: input.amount.toFixed(2), notes: input.notes }).where(eq(expenses.id, input.id)); return { success: true }; }), delete: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await dbOrThrow(); await db.delete(expenses).where(eq(expenses.id, input.id)); return { success: true }; }) }),

  activity: protectedProcedure.input(z.object({ limit: z.number().int().min(1).max(200).default(100) }).optional()).query(async ({ input }) => { const db = await dbOrThrow(); const [sales, free, payments, expenseRows, purchasesRows, customerRows] = await Promise.all([db.select().from(salesInvoices).orderBy(desc(salesInvoices.createdAt)).limit(200), db.select().from(freeInvoices).orderBy(desc(freeInvoices.createdAt)).limit(200), db.select().from(customerPayments).orderBy(desc(customerPayments.createdAt)).limit(200), db.select().from(expenses).orderBy(desc(expenses.createdAt)).limit(200), db.select().from(purchaseInvoices).orderBy(desc(purchaseInvoices.createdAt)).limit(200), db.select().from(customers)]); const names = new Map(customerRows.map((c) => [c.id, c.name])); const rows = [
      ...sales.map((x) => ({ id: `sale-${x.id}`, type: "sale", title: "فاتورة مخزنية", subtitle: x.customerId ? `حساب ${names.get(x.customerId) ?? "عميل"}` : "نقدي", amount: Number(x.total), createdAt: x.createdAt, referenceId: x.id })),
      ...free.map((x) => ({ id: `free-${x.id}`, type: "free", title: "فاتورة حرة", subtitle: x.customerName ? `حساب ${x.customerName}` : "بدون حساب", amount: Number(x.total), createdAt: x.createdAt, referenceId: x.id })),
      ...payments.map((x) => ({ id: `payment-${x.id}`, type: "payment", title: "دفعة حساب", subtitle: `حساب ${names.get(x.customerId) ?? "عميل"}`, amount: Number(x.amount), createdAt: x.createdAt, referenceId: x.id })),
      ...expenseRows.map((x) => ({ id: `expense-${x.id}`, type: "expense", title: "مصروف", subtitle: x.category, amount: Number(x.amount), createdAt: x.createdAt, referenceId: x.id })),
      ...purchasesRows.map((x) => ({ id: `purchase-${x.id}`, type: "purchase", title: "فاتورة شراء", subtitle: "المخزون", amount: Number(x.total), createdAt: x.createdAt, referenceId: x.id })),
    ].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).slice(0, input?.limit ?? 100); return rows; }),

  reports: router({
    summary: protectedProcedure.input(z.object({ from: z.coerce.date(), to: z.coerce.date() })).query(async ({ input }) => { const db = await dbOrThrow(); const [salesAgg, costAgg, purchaseAgg, expenseAgg, lowAgg, freeAgg] = await Promise.all([db.select({ total: sql<string>`COALESCE(SUM(${salesInvoices.total}),0)`, count: sql<number>`COUNT(*)` }).from(salesInvoices).where(and(gte(salesInvoices.createdAt, input.from), lt(salesInvoices.createdAt, input.to))), db.select({ total: sql<string>`COALESCE(SUM(${salesInvoiceItems.purchasePrice} * ${salesInvoiceItems.quantity}),0)` }).from(salesInvoiceItems).innerJoin(salesInvoices, eq(salesInvoiceItems.invoiceId, salesInvoices.id)).where(and(gte(salesInvoices.createdAt, input.from), lt(salesInvoices.createdAt, input.to))), db.select({ total: sql<string>`COALESCE(SUM(${purchaseInvoices.total}),0)` }).from(purchaseInvoices).where(and(gte(purchaseInvoices.createdAt, input.from), lt(purchaseInvoices.createdAt, input.to))), db.select({ total: sql<string>`COALESCE(SUM(${expenses.amount}),0)` }).from(expenses).where(and(gte(expenses.createdAt, input.from), lt(expenses.createdAt, input.to))), db.select({ count: sql<number>`COUNT(*)` }).from(products).where(and(eq(products.active, true), sql`CAST(${products.stock} AS DECIMAL(12,3)) <= CAST(${products.minStock} AS DECIMAL(12,3)`)), db.select({ total: sql<string>`COALESCE(SUM(${freeInvoices.total}),0)`, count: sql<number>`COUNT(*)` }).from(freeInvoices).where(and(gte(freeInvoices.createdAt, input.from), lt(freeInvoices.createdAt, input.to)))]); const sales = Number(salesAgg[0]?.total ?? 0); const freeSales = Number(freeAgg[0]?.total ?? 0); const costOfGoods = Number(costAgg[0]?.total ?? 0); const purchases = Number(purchaseAgg[0]?.total ?? 0); const expensesTotal = Number(expenseAgg[0]?.total ?? 0); const grossProfit = sales - costOfGoods; return { sales, freeSales, totalSales: sales + freeSales, invoices: Number(salesAgg[0]?.count ?? 0), freeInvoices: Number(freeAgg[0]?.count ?? 0), purchases, expenses: expensesTotal, costOfGoods, grossProfit, netProfit: grossProfit - expensesTotal, lowStock: Number(lowAgg[0]?.count ?? 0) }; }),
  }),

  settings: router({ get: protectedProcedure.query(async () => { const db = await dbOrThrow(); const row = (await db.select().from(storeSettings).limit(1))[0]; if (row) return row; await db.insert(storeSettings).values({}); return (await db.select().from(storeSettings).limit(1))[0]; }), update: protectedProcedure.input(z.object({ storeName: z.string().min(1).max(200), phone: z.string().optional(), address: z.string().optional(), currency: z.string().max(20), receiptWidth: z.enum(["58mm", "80mm"]), autoPrint: z.boolean().optional(), printCopies: z.number().int().min(1).max(9).optional(), showLogoOnReceipt: z.boolean().optional(), showUnitPriceOnReceipt: z.boolean().optional(), reportDefaultRange: z.string().max(20).optional(), lowStockAlerts: z.boolean().optional() })).mutation(async ({ input }) => { const db = await dbOrThrow(); const row = (await db.select().from(storeSettings).limit(1))[0]; if (row) await db.update(storeSettings).set(input).where(eq(storeSettings.id, row.id)); else await db.insert(storeSettings).values(input); return { success: true }; }) }),
});

export type AppRouter = typeof appRouter;
